--- 
objects: 
  - холодильник
  - утюг
  - цветок
  - человек
  - кошка
  - кот
  - собака
  - пёс
  - котенок
  - собакен
  - щенок
  - стул
  - стол
  - пальма
  - белка
  - утка
answers:
  - Я почти уверен, что это {{object}}. Так?
  - Это же {{object}}, верно?
  - Я на {{percent}}% уверен, что это {{object}}. Угадал?
  - Зуб даю это {{object}}, ага?
  - Может быть это {{object}}?
  - Мамой клянусь что это {{object}}. Да??
  - Это {{object}}, я прав?
  - Да это же {{object}}!!!
  - Утверждаю с точностью {{percent}}% что это {{object}}
yes_answers:
  - Ура :)
  - Отлично!
  - О да, я крут!
  - Я рад что тебе нравится как я работаю!
no_answers:
  - Не может быть :(
  - Да ты гонишь :(
  - Я же робот, я не мог ошибиться!
  - Подумаешь :P
  - Ну что же поделаешь. Давай еще раз?
  - В следующий раз я точно угадаю!
  - Эх, почти угадал
